INSERT INTO knowledge_documents (id, title, category, source, content, updated_at)
VALUES
  ('DOC-CATALOG-CLOTHING', 'Clothing Product Catalog', 'CATALOG', 'internal://catalog/clothing', 'Product ID, product name, and price: CLOTH-TEE-001 Classic Cotton White T-Shirt ¥99.00; CLOTH-SHIRT-002 Blue Oxford Shirt ¥199.00; CLOTH-JEANS-003 Straight-Leg Washed Jeans ¥299.00; CLOTH-HOODIE-004 Black Hooded Sweatshirt ¥259.00; CLOTH-DRESS-005 Floral Chiffon Dress ¥329.00; CLOTH-JACKET-006 Lightweight Windbreaker Jacket ¥399.00; CLOTH-SKIRT-007 High-Waist A-Line Skirt ¥189.00; CLOTH-POLO-008 Smart Casual Polo Shirt ¥169.00; CLOTH-COAT-009 Wool Blend Coat ¥699.00; CLOTH-SWEATER-010 Beige Knit Sweater ¥229.00.', CURRENT_TIMESTAMP(6));

INSERT INTO knowledge_chunks (id, document_id, title, category, source, content)
VALUES
  ('CHK-CATALOG-CLOTHING-TEE-001', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: Classic Cotton White T-Shirt', 'CATALOG', 'internal://catalog/clothing#CLOTH-TEE-001', 'Product ID CLOTH-TEE-001, product name Classic Cotton White T-Shirt, clothing product, price ¥99.00.'),
  ('CHK-CATALOG-CLOTHING-SHIRT-002', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: Blue Oxford Shirt', 'CATALOG', 'internal://catalog/clothing#CLOTH-SHIRT-002', 'Product ID CLOTH-SHIRT-002, product name Blue Oxford Shirt, clothing product, price ¥199.00.'),
  ('CHK-CATALOG-CLOTHING-JEANS-003', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: Straight-Leg Washed Jeans', 'CATALOG', 'internal://catalog/clothing#CLOTH-JEANS-003', 'Product ID CLOTH-JEANS-003, product name Straight-Leg Washed Jeans, clothing product, price ¥299.00.'),
  ('CHK-CATALOG-CLOTHING-HOODIE-004', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: Black Hooded Sweatshirt', 'CATALOG', 'internal://catalog/clothing#CLOTH-HOODIE-004', 'Product ID CLOTH-HOODIE-004, product name Black Hooded Sweatshirt, clothing product, price ¥259.00.'),
  ('CHK-CATALOG-CLOTHING-DRESS-005', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: Floral Chiffon Dress', 'CATALOG', 'internal://catalog/clothing#CLOTH-DRESS-005', 'Product ID CLOTH-DRESS-005, product name Floral Chiffon Dress, clothing product, price ¥329.00.'),
  ('CHK-CATALOG-CLOTHING-JACKET-006', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: Lightweight Windbreaker Jacket', 'CATALOG', 'internal://catalog/clothing#CLOTH-JACKET-006', 'Product ID CLOTH-JACKET-006, product name Lightweight Windbreaker Jacket, clothing product, price ¥399.00.'),
  ('CHK-CATALOG-CLOTHING-SKIRT-007', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: High-Waist A-Line Skirt', 'CATALOG', 'internal://catalog/clothing#CLOTH-SKIRT-007', 'Product ID CLOTH-SKIRT-007, product name High-Waist A-Line Skirt, clothing product, price ¥189.00.'),
  ('CHK-CATALOG-CLOTHING-POLO-008', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: Smart Casual Polo Shirt', 'CATALOG', 'internal://catalog/clothing#CLOTH-POLO-008', 'Product ID CLOTH-POLO-008, product name Smart Casual Polo Shirt, clothing product, price ¥169.00.'),
  ('CHK-CATALOG-CLOTHING-COAT-009', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: Wool Blend Coat', 'CATALOG', 'internal://catalog/clothing#CLOTH-COAT-009', 'Product ID CLOTH-COAT-009, product name Wool Blend Coat, clothing product, price ¥699.00.'),
  ('CHK-CATALOG-CLOTHING-SWEATER-010', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: Beige Knit Sweater', 'CATALOG', 'internal://catalog/clothing#CLOTH-SWEATER-010', 'Product ID CLOTH-SWEATER-010, product name Beige Knit Sweater, clothing product, price ¥229.00.'),
  ('CHK-CATALOG-CLOTHING-ALL', 'DOC-CATALOG-CLOTHING', 'Clothing Catalog: Complete Price List', 'CATALOG', 'internal://catalog/clothing#all', 'Complete clothing catalog: Classic Cotton White T-Shirt CLOTH-TEE-001 ¥99.00; Blue Oxford Shirt CLOTH-SHIRT-002 ¥199.00; Straight-Leg Washed Jeans CLOTH-JEANS-003 ¥299.00; Black Hooded Sweatshirt CLOTH-HOODIE-004 ¥259.00; Floral Chiffon Dress CLOTH-DRESS-005 ¥329.00; Lightweight Windbreaker Jacket CLOTH-JACKET-006 ¥399.00; High-Waist A-Line Skirt CLOTH-SKIRT-007 ¥189.00; Smart Casual Polo Shirt CLOTH-POLO-008 ¥169.00; Wool Blend Coat CLOTH-COAT-009 ¥699.00; Beige Knit Sweater CLOTH-SWEATER-010 ¥229.00.');
